# Generated by Django 3.1.5 on 2021-01-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
